### ISSUE TITLE
Адаптивная / резиновая вёрстка + mobile first + понятие брейкпоинтов

### ISSUE THREAD

**Issue by solarrust** [Y-Doka/y-doka.site#107]

**Comment by solarrust** [comment]
После написания добавить в список статей для спринта №3

**Comment by solarrust** [comment]
Появилась мысль, что стоит разбить на отдельные статьи:
1. Отличия адаптивной от резиновой вёрстки
2. Mobile First против Desctop First
3. Брейкпоинты: понятие и расстановка

@ezhkov @Realetive хочу услышать ваши мнения

**Comment by Realetive** [comment]
Думаю, стоит попробовать. Вообще темы очень пересекаются, поэтому нужно понять — какую «проблему» мы хотим решить — для последовательного вдумчивого чтения, думаю, «разбивка» была бы удобнее 👍

**Comment by solarrust** [comment]
@Realetive в моей голове есть следующие цели:
1. Не перегружать ненужной инфой человека, который хочет прочитать только про один-два из этих понятий
2. Заполучить побольше релевантных страничек

**Comment by solarrust** [comment]
Закрою, пожалуй, этот здоровенный всеобъемлющий ишью и заведу отдельные на каждую тему
