### ISSUE TITLE
Отсортировать статьи в разделе JS по алфавиту

### ISSUE THREAD

**Issue by nlopin** [Y-Doka/y-doka.site#191]
## Проблема

Статьи в боковом меню сейчас отсортированы по дате добавления, из-за этого сложно искать по ним глазами и приходится использовать поиск

## Что делать

Посмотреть [раздел документации о сортировке коллекций](https://www.11ty.dev/docs/collections/#sorting) и воспользоваться рецептом оттуда.

Другой вариант — подсмотреть, как это сделано в разделе CSS. Там сортировка верная

**Comment by maximumsweet** [comment]
Возможно я чего-то не понимаю, но по-моему реализация сортировки в CSS и JS использована одинаковая. Так ли это?

**Comment by nlopin** [comment]
Похоже, что так. Значит нужно везде чинить. 

Сейчас смущает, что языки перемешаны. Кажется сортировка происходит по `name` статьи, а он всегда на английском. Нужно для сортировки использовать `title`
