### ISSUE TITLE
Добавить статью «Webpack, краткий обзор» в инструменты

### ISSUE THREAD

**Issue by nlopin** [Y-Doka/y-doka.site#194]
Верхнеуровневый рассказ про вебпак

**Comment by igorkamyshev** [comment]
Смущает тег "лонгрид", я планировал это как небольшую статью с инструкцией по настройке и базовым концепциям. Ты видишь это как-то иначе?

**Comment by pepelsbey** [comment]
Кажется лонгрид в нынешней системе это просто «не дока». Не знаю, если ли требования, насколько «лонг» должен быть этот «рид».
