### ISSUE TITLE
Callout → `<aside>`?

### ISSUE THREAD

**Issue by bespoyasov** [Y-Doka/y-doka.site#202]
Я думаю, тег `<mark>` хорошо подойдёт для кричалок. 
Это по сути выделение маркером, этакий хайлайт; что думаете?

<img width="1106" alt="«Screenshot» 2020-11-30 at 19 11 43" src="https://user-images.githubusercontent.com/9102374/100634238-13eaa380-3340-11eb-9514-68215b2f172e.png">

**Comment by pepelsbey** [comment]
[Mark он фразовый](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-mark-element), то есть внутри параграфа выделение, рядом с текстом. Тут [лучше aside](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element), как по мне.

**Comment by furtivite** [comment]
Там где можно использовать markdown, лучше использовать его и посмотреть как такая штука реализована в том же notion и сделать по подобию. 

Для быстрого решения можно использовать и html, тогда надо 
- Сделать файл с примерами таких вызовов, чтобы все могли пользоваться, нам нужны варианты с лампочкой (наверное, как модификатор к классу), с восклицательным знаком
- Надо написать, что после использования html нужно оставлять пустую строку и внутри этой обёртки всё равно лучше использовать markdown, чтобы не иметь 2 типа кода в одном месте, например

```

<aside class="callout callout_lamp">

    Эта документация связана с понятием асинхронности в JavaScript. Зачем нужен асинхронный код, и как он работает, описано в обзорной статье [Асинхронность в JS]()

</aside>


```

**Comment by bespoyasov** [comment]
> как такая штука реализована в том же notion и сделать по подобию.

Notion с этим вообще не парится, он callout преобразует в обычный параграф :–( 
Я согласен, что лучше везде использовать md, но он очень скудный (хотя альтернативы я ему не знаю всё равно).

> Сделать файл с примерами таких вызовов, чтобы все могли пользоваться, нам нужны варианты с лампочкой (наверное, как модификатор к классу), с восклицательным знаком
> Надо написать, что после использования html нужно оставлять пустую строку и внутри этой обёртки всё равно лучше использовать markdown, чтобы не иметь 2 типа кода в одном месте, например

Много ограничений получается, опен-сорс с этим не полетит :–) 
В идеале нам нужно, чтобы всё «просто работало».

Если у нас будет собственный AST-парсер, то это ты решилось через конструкцию типа ```callout-lamp ...
Исходник как у блока с кодом, но на выходе — `aside` с нужным классом. 

Парсер — это дорого, но он уже второй раз пригодился бы. Есть у меня ощущение, что им бы можно будет воспользоваться ещё где-то.

**Comment by furtivite** [comment]
Кстати, ощущение, что у notion, всё же, какой-то парсер есть, потому как при экспорте в html он опять же оборачивает в `<figure>`

![2020-12-01_11-08-40](https://user-images.githubusercontent.com/50330458/100713693-b862f900-33c5-11eb-9c25-0c3162b31a32.png)

> Много ограничений получается, опен-сорс с этим не полетит :–)
> В идеале нам нужно, чтобы всё «просто работало».

Проблема с пустыми пробелами есть в eleventy уже сейчас и это реальное ограничение, с которым можно столкнуться уже сейчас, к сожалению.

**Comment by bespoyasov** [comment]
> Для быстрого решения можно использовать и html, тогда надо
> Сделать файл с примерами таких вызовов, чтобы все могли пользоваться, нам нужны варианты с лампочкой (наверное, как модификатор к классу), с восклицательным знаком
> Надо написать, что после использования html нужно оставлять пустую строку и внутри этой обёртки всё равно лучше использовать markdown, чтобы не иметь 2 типа кода в одном месте, например

Тогда я, пожалуй, соглашусь вот с этим пока что; написать парсер за пару дней я не смогу 😅

В статье о рекурсии уже начал использовать `aside` в виде HTML.

**Comment by nlopin** [comment]
У ноушена скорее всего есть внутреннее представление блоков, которое они умеют рендерить в разные форматы. Так как мы живем в markdown, думаю стоит подумать над своим flavor.

Я немного покопался и кажется это не так сложно, как кажется. Для начала можно посмотреть плагины к markdown-it, 
[markdown-it-container](https://www.npmjs.com/package/markdown-it-container) выглядит подходящим

**Comment by bespoyasov** [comment]
Восхитительно!

Тогда это, скорее всего, отдельная ишья, а эту можно закрывать.

**Comment by nlopin** [comment]
Создал #217, обсуждение закрываю
