### ISSUE TITLE
Подписи к картинкам в `figcaption`?

### ISSUE THREAD

**Issue by bespoyasov** [Y-Doka/y-doka.site#205]
Кажется, картинки с видимыми подписями стоит положить в `figure`, а сами такие подписи — в `figcaption`. 

Иногда подписи к картинкам относятся к тексту опосредованно, а скорее поясняют изображение и то, как оно относится к тексту. Такие подписи лучше несколько отделять стилями от основного полотна, потому что это может сбивать с толку.

Ниже пример из Notion, из контекста понятно, что стрелки не нужно искать где-то в тексте выше, потому что это объяснение изображения:
<img width="733" alt="«Screenshot» 2020-11-30 at 21 53 17" src="https://user-images.githubusercontent.com/9102374/100651629-c6c5fc00-3356-11eb-95ed-9fbc925a0223.png">

Пример из Доки, неясно, о каких стрелках речь, и почему для них мы отвели целый параграф:
<img width="846" alt="«Screenshot» 2020-11-30 at 22 00 28" src="https://user-images.githubusercontent.com/9102374/100652118-7e5b0e00-3357-11eb-9191-816ff512b68f.png">

Не все картинки с подписями, это правда, но я в лонгридах очень часто использую иллюстрации-метафоры, которые «приклеиваю» подписями к основному тексту. Это помогает ментальную модель упростить при объяснении.

**Comment by nlopin** [comment]
Главный вопрос: насколько это возможно сделать через маркдаун? 

Альтернативно можно вставлять картинки обычным html, но это мне кажется слишком крайняя мера

**Comment by bespoyasov** [comment]
В маркдауне, кажется, такого нет. По крайней мере я для своего сайта [костылил компонент](https://github.com/bespoyasov/www/blob/master/components/Figure/Figure.tsx), на который потом `@mdxjs` заменяет [обычные картинки в `.md`-файлах](https://github.com/bespoyasov/www/blob/master/pages/blog/new-site-stack.mdx#frontmatter):
<img width="869" alt="«Screenshot» 2020-11-30 at 22 21 06" src="https://user-images.githubusercontent.com/9102374/100654073-5d47ec80-335a-11eb-9e79-9111016c34d7.png">

Не знаю, есть ли в Eleventy возможность сделать нечто подобное и не будет ли это оверхедом.

Я в крайнем случае готов мириться с тем, чтобы в своих статьях писать руками `<figure><img /><figcaption>...</figcaption></figure>` 😃 

Если мы этого делать не хотим, то мне нужно будет просмотреть все свои статьи и переписать пояснения.

**Comment by pepelsbey** [comment]
Положить картинки в figure + figcation — отличная идея. Понятнее и проще всего будет ввести правило, что все картинки пишутся в HTML: так проще вешать классы (в какой-то момент это пригодится) и проще понимать авторам, не нужно учить какие-то шорткоды.

**Comment by furtivite** [comment]
Честно говоря, я бы предпочёл markdown везде, где можно использовать markdown, а не html. 

Если посмотреть в Notion, который тоже использует markdown, то там есть подписи у картинок. 

![2020-12-01_10-26-14](https://user-images.githubusercontent.com/50330458/100710183-653a7780-33c0-11eb-80fb-5704e0a55a1a.png)

При экспорте в виде markdown эта подпись = первый параграф после картинки

![2020-12-01_10-26-39](https://user-images.githubusercontent.com/50330458/100710242-7d11fb80-33c0-11eb-8737-5845a5b1bdf0.png)

А если экспортировать в виде HTML-файла мы получаем тот самый <figcapture>

![2020-12-01_10-31-07](https://user-images.githubusercontent.com/50330458/100710322-94e97f80-33c0-11eb-9e99-a059bc9a569d.png)

Значит они каким-то образом это сделали и стоит узнать каким.

**Comment by furtivite** [comment]
С другой стороны можно использовать и figure + figcation, как предлагает @pepelsbey, но у нас возникает список вопросов:
- Надо ли переделывать в эту конструкцию существующие картинки?
    - Если нет, как объяснить, почему у нас рядом 2 конструкции
    - Если да, то надо сделать issue
- Если приходим к такому решению, то надо внести это в правила оформления статей и напомнить, что после html-кода надо отбивать строку, чтобы eleventy снова начал понимать, что перед ним markdown
- Не появится ли у нас куча классов от контрибуторов, которые решат поставить картинку, например, по центру, если это не предусмотрено дизайном?

**Comment by bespoyasov** [comment]
> Честно говоря, я бы предпочёл markdown везде, где можно использовать markdown, а не html.

➕ 

> При экспорте в виде markdown эта подпись = первый параграф после картинки
> При экспорте в виде markdown эта подпись = первый параграф после картинки
> Значит они каким-то образом это сделали и стоит узнать каким.

🔥 

P.S. Думаю, это у них какой-то волшебный AST-парсер.
P.P.S. Нам, возможно, и сами понадобится подобный парсер, если мы хотим использовать только `md`, но при этом иметь возможность ставить классы картинкам. Например, [`remark-attr`](https://github.com/arobase-che/remark-attr) позволяет добавлять атрибуты (классы в том числе) изображениям в `md`.

**Comment by pepelsbey** [comment]
Я ещё даже не начал, но планирую чаще говорить про доступность тех решений, которые мы рекомендуем в документации и сами используем на сайте. Так вот параграф текста сразу после картинки никак не привязан к ней и не является её дополнительным описанием. А если это figure + figcaption — всё как надо.

**Comment by furtivite** [comment]
@pepelsbey я согласен, что параграф текста после картинки никак к ней не привязан и не является её описанием. Плюс к тому, есть картинки без подписи и там тоже должно быть точное решение. У notion явно есть какой-то парсер, про который говорит @bespoyasov, надо скорее всего приходить к такому решению. 

Пока что решить как будем делать на промежуточном этапе.

**Comment by bespoyasov** [comment]
В статье о рекурсии я пока что ставлю руками `figure + figcaption`. Думаю, если понадобится, смогу пройтись и по всем своим старым статьям и обновить подписи.

Обновлять ли другие подписи к картинкам, думаю, стоит решить уже всем вместе.

**Comment by bespoyasov** [comment]
@nlopin, кажется, [нашёл подходящее решение](https://github.com/Y-Doka/y-doka.site/issues/202#issuecomment-736775858) для проблемы с md.

**Comment by usmanyunusov** [comment]
@bespoyasov как думаешь, такой синтаксис приемлем для картинок? (заканчиваю плагин для md)
`#!классДляТегаFigure[Описание картинки](/assets/images/posts/js/debounce/debounce-diagram.png [Alt для тега img])`

В итоге html будет таким:

```
<figure class="doka-figure__классДляТегаFigure">
    <img src="/assets/images/posts/js/debounce/debounce-diagram.png" alt="Alt для тега img">
    <figcaption>Описание картинки</figcaption>
</figure>
```

**Comment by bespoyasov** [comment]
Мне нравится синтаксис атрибутов у [`remark-attr`](https://github.com/arobase-che/remark-attr):

```
![Description](img){ class="someClass" }
```

## Разница между `alt` и `figcaption`

Они хоть и не заменяют друг друга, но я думаю, что так как мы чаще всего собираемся использовать `figure` вместе с изображением, то в большинстве случаев `alt` и `figcaption` могут совпадать. 

Если же в `alt` потребуется дописать то, чего нет в `figcaption`, то запись с атрибутами будет читаться проще:

```
![Description](img){ class="someClass", alt="Alt text" }
```

## В чём плюсы
- это более общее решение, если нам потребуется указывать `with` или `height` или другие атрибуты для изображений, нам не придётся выдумывать новый синтаксис;
- мы можем использовать фолбеки для классов и `alt`-текста из того, что уже имеем;
- не требуется создавать (и учить) новый синтаксис на каждую новую фичу.

В итоге получим:

```
![Description](imgSource)

=>

<figure class="figure">
  <img src="imgSource" alt="Description" />
  </figcaption>Description</figcaption>
</figure>
```

А при использовании атрибутов можем композировать их значения с имеющимися:

```
![Description](imgSource){ class="someOtherClass", alt="Alt text", with=700, loading="lazy" }

=>

<figure class="figure someOtherClass">
  <img src="imgSource" alt="Alt text" width="700" loading="lazy" />
  </figcaption>Description</figcaption>
</figure>
```

@nlopin, @pepelsbey, @solarrust, что думаете?

**Comment by pepelsbey** [comment]
Я знаю что это такое с первого взгляда, в самой глубине души. И не только я, любой внешний автор:

```html
<figure class="figure someOtherClass">
  <img src="imgSource" alt="Alt text" width="700" loading="lazy" />
  </figcaption>Description</figcaption>
</figure>
```

А вот что это такое… ещё придётся разобраться. И мне, и внешним авторам. Особенно если сюда добавить реальный alt-текст и реальную подпись для figcaption.

```md
![Description](imgSource){ class="someOtherClass", alt="Alt text", with=700, loading="lazy" }
```

Мне кажется, что нам стоит оставить HTML для таблиц и фигур. Ну нельзя их сделать хорошо в маркдауне, просто нельзя. Ширины колонок, подписи, всё сложнее примеров.

**Comment by bespoyasov** [comment]
Я не против HTML: последние лонгриды я писал, используя plain HTML. Мне интересно, что думают @nlopin, @solarrust, @furtivite, @igorkamyshev, @Windrushfarer, @Realetive и @ezhkov.

**Comment by nlopin** [comment]
Давайте пока пойдем по пути наименьшего сопротивления и будем использовать HTML для всего сложного. Если захотим, то дальше сделаем кастомный рендеринг `![]()`

**Comment by Windrushfarer** [comment]
Идея держать какие-то сниппеты HTML для сложных штук мне нравится. Все-таки хочется больше именно работать с md и текстом.

**Comment by pepelsbey** [comment]
> сниппеты HTML для сложных штук

Вот именно: если сделать хорошее руководство для создания статей (по следам вёрстки этих статей) с примерами вставки сложных вещей, вроде таблиц, картинок с подписями и подобного — не нужно будет думать, нужно будет копировать и вставлять.
