### ISSUE TITLE
Сверстать блок «контрибуторы»

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#209]
Необходимо сверстать блок "контрибуторы".

## Требования

- Блок располагается в отдельном *.njk-файле в папке `/src/includes/contributors/`
- Стили блока написаны в *.scss-файле в папке `/src/assets/styles/components/`
- Если используется JS, он лежит в папке `/src/assets/scripts/modules/`
- Блок блок свёртан по БЭМ и может быть переиспользован многократно в любом месте
- Все картинки имеют alt-описание
- Элементы блока
    - Имя автора - это всегда ссылка в новой вкладке на страницу автора
    - Иконка социальной сети — ссылка в новой вкладке на социальную сеть автора
        - При наведении мышкой на иконку социальной сети, она раскрашивается в фирменные цвета социальной сети
        - При попадании клавиатурой на иконку социальной сети, происходит тоже самое, что и при наведении мышкой
        - Допустим вариант, когда иконок социальной сети у автора нет
    - Оранжевый круг (на примере одного автора) — аватар. Аватар — это ссылка в новой вкладке на страницу автора
        - Если авторов несколько, круг чёрный
    - Если авторов несколько, пишем "Несколько авторов"
        - При клике на "несколько авторов" открывается блок, в котором перечислены все авторы со ссылками на социальные сети, но без аватаров и без указания даты
        - При клике на имя автора или социальную сеть, происходит тоже самое, как если бы автор был один

### Примечания

Вы можете сверстать 2 блока: под одного автора и под нескольких авторов.

Вы можете подготовить блок таким образом, чтобы он принимал значения авторов из *.md-файла в папке `/src/posts/`, в котором находится.

## Дизайн

[Посмотреть в figma](https://www.figma.com/file/pgLmvK5Ajz6A7uyh3B2mUc/Autors-public?node-id=0%3A1)

### Превью
- Один автор
    ![Один автор](https://user-images.githubusercontent.com/50330458/100708776-f78d4c00-33bd-11eb-8268-d4bec6788f7f.jpg)
- Несколько авторов
    ![Несколько авторов](https://user-images.githubusercontent.com/50330458/100708780-f9570f80-33bd-11eb-9623-667fa0af0346.jpg)
- Несколько авторов. Мышка на заголовке
    ![Несколько авторов. Мышка на заголовке](https://user-images.githubusercontent.com/50330458/100708785-fb20d300-33bd-11eb-94d8-f985b306361c.jpg)
- Несколько авторов. Мышка на авторе
    ![Несколько авторов. Мышка на авторе](https://user-images.githubusercontent.com/50330458/100708787-fc520000-33bd-11eb-8fd6-81164a8c424a.jpg)

**Comment by usmanyunusov** [comment]
Начал верстку блока - https://github.com/Y-Doka/y-doka.site/pull/213
Какая именно структура данных  у contributors будет в постах?

**Comment by furtivite** [comment]
@usmanyunusov планировалось, что будет приходить [коллекция 11ty](https://www.11ty.dev/docs/collections/). Круто, что присоединился! 🖖

**Comment by usmanyunusov** [comment]
```
---
title: <a>
name: a
author: grachev
co-authors:
  - ABatickaya
designers:
contributors: skorobaeus
summary:
  - ссылка
  - <a>
  - a
  - тэг
  - тег
---
```

В постах сейчас структура такая. В блоке **контрибуторы** есть картинки, ссылки и тд. Откуда для них данные будут приходить? Данные для контрибуторов в постах будут или отдельной коллекцией?

**Comment by furtivite** [comment]
@usmanyunusov предполагалось, что будет отдельный массив с данными для контрибуторов, там будет Имя, Фамилия, ссылки на социальные сети и страницу, при клике на имя, пользователь будет попадать на отдельную страницу контрибутора, там тоже будут свои данные, но это другая задача, там можно будет просто в md положить и сверстать отдельную страницу, эта задача появится позже.

**Comment by nlopin** [comment]
Давай просто заведем json файл с данными контрибьюторов и будем брать из него по ключу.

Формат такой:
```
{
  "ivanov": {
    "firstName": "Ivan",
    "lastName": "Ivanov",
    "twitter": "iivanov",
    ...
  }
}
```

Можно попробовать коллекцией, но я не понимаю, как это будет работать

**Comment by pepelsbey** [comment]
JSON для машин, людям проще писать YAML, вот как мы в Веб-стандартах [храним профили людей](https://raw.githubusercontent.com/web-standards-ru/web-standards.ru/master/src/people/addy-osmani/index.md):

```
---
name: Эдди Османи
url: https://addyosmani.com/
tags: people
photo: true
permalink: false
---
```

**Comment by usmanyunusov** [comment]
@furtivite, @nlopin давайте рассмотрим предложение @pepelsbey. На примере Веб-стандарт попробую создать отдельную папку для контрибюторов и реализовать пример.

**Comment by furtivite** [comment]
@usmanyunusov круто! Можно вот [здесь](https://github.com/Y-Doka/y-doka.site/tree/master/src/includes/authors)?
