### ISSUE TITLE
Изображения могут не помещаться в экран

### ISSUE THREAD

**Issue by bespoyasov** [Y-Doka/y-doka.site#216]
Если изображение слишком высокое, оно [не помещается в экран](https://y-doka.site/posts/js/long/oop/) по высоте:
<img width="1680" alt="Screenshot 2020-12-01 at 22 57 54" src="https://user-images.githubusercontent.com/9102374/100791018-b7fc4980-3429-11eb-86fe-30cbf7c6048e.png">

Можно решить через `max-height: 90vh` (или какое-то другое значение):
<img width="1174" alt="Screenshot 2020-12-01 at 23 09 13" src="https://user-images.githubusercontent.com/9102374/100791428-4e306f80-342a-11eb-86fe-f66473a01819.png">

**Comment by ezhkov** [comment]
Я бы предложил в дополнение к этому как-то готовить предварительно картинку. Как минимум скриншоты с ретины уменьшать до 1х.

**Comment by bespoyasov** [comment]
Ещё в рамках обсуждения — ограничение в `max-width` по ширине у нас есть только для картинок внутри параграфов: 

```css
p img { max-width: 100%; }
````

Мне кажется, лучше сделать это для любых контентых картинок, которые лежат внутри `.article`. Иначе при использовании другого элемента (того же `figure`) [адаптивность теряется](https://deploy-preview-206--y-doka.netlify.app/posts/js/long/recursion/):
<img width="907" alt="Screenshot 2020-12-01 at 23 15 04" src="https://user-images.githubusercontent.com/9102374/100791997-0d852600-342b-11eb-8686-885ff2bc2b06.png">

**Comment by bespoyasov** [comment]
> Я бы предложил в дополнение к этому как-то готовить предварительно картинку. Как минимум скриншоты с ретины уменьшать до 1х.

Насколько я понимаю, все скриншоты дизайнеры оформляют в виде тёмного фона со скриншотом по центру. Я поэтому не стал их переделывать ¯\_(ツ)_/¯ 

Если потребуется — обновлю, конечно.
