### ISSUE TITLE
Научить маркдаун делать details блок 

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#218]
## О чем это?

В статьях предусмотрены блоки в которых скрывается часть информации

![2020-12-01_23-29-32](https://user-images.githubusercontent.com/50330458/100793443-255da980-342d-11eb-8eee-ff357a570225.png)
Блок закрыт

![2020-12-01_23-29-40](https://user-images.githubusercontent.com/50330458/100793446-268ed680-342d-11eb-8c90-6721a62d63b4.png)
Блок открыт

Сейчас мы используем html-теги 

```html
<details>
    <summary>Типы</summary>
</details>
```

## Что должно получиться?
Хочется писать в маркдауне что-то типа

```markdown
>>>
>Типы
Какой-то контент
>>>
```
и получать при рендеринге в html блок 

```html
<details>
    <summary>Типы</summary>
</details>
```

## Что надо делать?
Нужно изучить плагины к markdown-it и найти подходящий. Хорошим местом для старта будет плагин
[markdown-it-container](https://www.npmjs.com/package/markdown-it-container)

**Comment by pepelsbey** [comment]
У нас кажется есть беда с этими задачами по внедрению тегов: мы пытаемся расширить маркдаун и теперь недостаточно будет знать базовый синтаксис, придётся учить новый.

Я бы предложил настроить markdown-it так, чтобы маркдаун обрабатывался и внутри тегов (кажется есть такой вариант) и тогда можно будет писать прямо в статьях:

```html
<aside>
    Blah [link](…) Blah `code` Blah
</aside>
```

И оно будет работать. Это точно лучше, чем придумывать новый язык, по-моему.

**Comment by pepelsbey** [comment]
Могу ошибаться, но кажется это [`html: true`](https://markdown-it.github.io/markdown-it/#MarkdownIt.new)

<img width="622" alt="image" src="https://user-images.githubusercontent.com/105274/100795621-64d9c500-3430-11eb-9e4d-9d6b6b2e9320.png">

**Comment by nlopin** [comment]
Он уже true, так что можно html безнаказанно вставлять

**Comment by pepelsbey** [comment]
@nlopin но я правильно понял, что теперь внутри тегов тоже маркдаун обрабатывается или это про другое настройка? Так точно можно было в Kramdown, а вот про markdown-it я не уверен.

**Comment by furtivite** [comment]
@pepelsbey внутрь тегов можно вставлять маркдаун, но нужны пустые строки между маркдауном и текстом. 

например

<details class="article__table article__table_all-half">
  <summary>Типы 🤖</summary>

| HTML 4.01 |  |
| --- | --- |
| `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">` | Строгий синтаксис HTML |
| `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">` | Переходный синтаксис HTML |
| `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">` | В HTML-документе применяются фреймы |

</details>

[Как тут](https://github.com/Y-Doka/y-doka.site/blob/master/src/posts/html/doka/doctype.md)

**Comment by pepelsbey** [comment]
Ага, значит уже работает, огонь.

**Comment by furtivite** [comment]
Issue закрыт. Мы пользуемся `<details>` на практике. Возможно, в дальнейшем, мы вернёмся к этому вопросу.
