### ISSUE TITLE
Текст заголовка не вмещается в экран телефона

### ISSUE THREAD

**Issue by bespoyasov** [Y-Doka/y-doka.site#300]
iPhone 11, [статья о безопасности приложений](https://github.com/posts/js/long/web-security/):

![Статья о безопасности](https://user-images.githubusercontent.com/9102374/101128994-d2911700-3611-11eb-85a9-eb04a551bc9c.png)

Уменьшим кегль на узких экранах?

**Comment by solarrust** [comment]
У нас в принципе пока не оч с адаптивом, это большая отдельная задача. Есть быстрое решение: 
```
white-space: pre-wrap;
word-break: break-word;
hyphens: auto;
```

**Comment by bespoyasov** [comment]
Не, я не думаю, что надо костылить. 

А у нас уже есть задача про адаптив? Если да, я эту закрою. Если нет, то переименую.

**Comment by furtivite** [comment]
Вообще надо ставить большую задачу про адаптив, я за решение Алёны, плюс добавить 

`font-size: 0.75em;`

Это позволит уменьшить размер текста и длинное слово не будет обрезаться. 

Есть ещё для длинных слов в заголовках добавлять где-то посередине по правилам русского языка тег `&shy;`, это сделает перенос, но я не в курсе как это с СЕО вяжется.

**Comment by furtivite** [comment]
Апдейт, я нашел в фигме дизайн и сделаю сегодня ишью на эту тему,

**Comment by bespoyasov** [comment]
Я не хочу делать точечных решений, это несистемно. 

Моё предложение — собирать все такие вещи в одном месте, чтобы потом исправить их учитывая вообще всё, что насобирали.

**Comment by furtivite** [comment]
@bespoyasov , вроде как он готов, перепроверим и сегодня будет ишью)

**Comment by bespoyasov** [comment]
Гуд, тогда я эту закрою 👍
