### ISSUE TITLE
Определиться с написанием слова т[еэ]г

### ISSUE THREAD

**Issue by nikolai-shabalin** [Y-Doka/y-doka.site#302]
На сайте написание слова тег разное, то "т**э**г", то "т**е**г".

Нужно определиться с написанием и придерживаться одного.

Предложу через "е", так как в Веб-стандартах уже обсуждали - https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#tag

**Comment by pepelsbey** [comment]
[Основная статья](https://ru.wiktionary.org/wiki/%D1%82%D0%B5%D0%B3) Викисловаря тоже про «тег».

**Comment by furtivite** [comment]
Мы приходим к [словарю веб-стандартов](https://github.com/web-standards-ru/dictionary/blob/master/dictionary.md#t), так что правильно - тег. Надо сделать замену по вхождению.
