### ISSUE TITLE
Определиться с написанием слова оверл[эе]й

### ISSUE THREAD

**Issue by nikolai-shabalin** [Y-Doka/y-doka.site#304]
В проекте встречается и "оверл**э**й" и "оверл**е**й".

У меня особых претензий к любому написанию нет. Тут больше вопрос про единообразие написания.

**Comment by pepelsbey** [comment]
[Викисловарь за -лей](https://ru.wiktionary.org/wiki/overlay), я тоже

**Comment by nlopin** [comment]
@pepelsbey мы договаривались использовать словарь Веб-стандартов. Думаешь имеет смысл подкидывать в него слова, которые мы встречаем или все-таки это слишком узконаправленные?

**Comment by pepelsbey** [comment]
Да, давайте я добавлю в словарь. Вполне нормальные термины для него, особенно если есть сложности.
