### ISSUE TITLE
Обновить normalize

### ISSUE THREAD

**Issue by nikolai-shabalin** [Y-Doka/y-doka.site#306]
Сейчас в проекте [normalize v3.0.3](https://github.com/Y-Doka/y-doka.site/blob/6467a48f40dc5f18486ded5d602bedcb67e64ef5/src/assets/styles/base/_normalize.scss#L1), но он уже [v8.0.1](https://github.com/necolas/normalize.css).

Хотели бы обновить?

**Comment by pepelsbey** [comment]
[v3.0.3 был 2015 году](https://github.com/necolas/normalize.css/releases/tag/3.0.3), ой 😅

**Comment by nlopin** [comment]
Молодец, что заметил! Я сейчас пересматриваю нашу сборку и такие замечания очень кстати 👍
