### ISSUE TITLE
Добавить в package.json конфиг browserlist

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#318]
Это нужно для задачи #317 и любых других инструментов, которые собирают код — чтобы не шипить лишний код. Предлагаю такой:

```json
  "browserslist": [
    "last 2 version",
    "not dead",
    "not ie <= 11"
  ],
```

По сути, это список браузеров, которые мы поддерживаем в коде сайта — browserslist.dev

**Comment by nlopin** [comment]
Я предлагаю IE 11 прибить. Если смотреть [статистику по России](https://radar.yandex.ru/browsers?group=month&selected_rows=Ct58LP%252CRysHuf%252CnmpVtr), то там меньше процента.

Это не жесткая позиция, допускаю, что в разделе верстки иметь IE критично.

**Comment by pepelsbey** [comment]
@nlopin `"not ie <= 11"` нужен для того, чтобы `last 2 version` не подцепил IE.

**Comment by nlopin** [comment]
Точняк, я почему-то решил, что мы 11 оставляем 🤦🤦🤦
