### ISSUE TITLE
Не та статья подсвечивается

### ISSUE THREAD

**Issue by solarrust** [Y-Doka/y-doka.site#321]
При открытии нескольких статей из раздела HTML и CSS неправильно отрабатывает подсветка активной статьи в боковой колонке. 
Пример: статья про `<html>`, а в боковой колонке подсвечивается статья про `<a>`. 
https://y-doka.site/posts/html/doka/html/

**Comment by ezhkov** [comment]
Duplicate of #214

**Comment by ezhkov** [comment]
#214

**Comment by solarrust** [comment]
@ezhkov твоя правда, спасибо!
