### ISSUE TITLE
Привести title к строке

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#334]
У нас сейчас h1-заголовки статей указаны простым текстом, например:

```markdown
title: Системы сборки
```

Из-за этого сборка может ломаться, например, если мы выводим спецсимволы в title, например при описании @-правил:

```markdown
title: @import
```
см. PR #333 

Чтобы такого не происходило, нужно заменить всё содержимое `title` на значения в одинарных кавычках:

```markdown
title: 'Системы сборки'
```

```markdown
title: '@import'
```

**Comment by maximumsweet** [comment]
Обязательно ли использовать одинарные ковычки?
Дело в том, что при коммите у меня автоматически меняются одинарные ковычки на двойные, не пойму в чем дело. В моём prettier.cfg по одинарным ковычкам стоит true, а в проектный prettier и editorsconfig не хотелось бы лезть без вашего согласования.

**Comment by maximumsweet** [comment]
Да, дело оказалось в файле `.editorconfig`, похоже он переопределяет любые настройки для vscode, prettier, tslint и т. д. и, похоже, по умолчанию использует двойные кавычки, вместо одинарных кавычек.
После добавления строки `quote_type = single` - двойные кавычки перестали автозаменяться. Но теперь проблема в другом, все двойные кавычки теперь стали одинарными в изменяемых файлах.
`quote_type = auto` что-то не помогает.
@furtivite прошу дать фидбек)

**Comment by maximumsweet** [comment]
Думаю данный issue можно закрыть.

**Comment by pepelsbey** [comment]
Всем спасибо :)
