### ISSUE TITLE
Сгруппировать все ресурсы материалов

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#345]
Предложение, которое поможет улучшить модульность материалов. Давайте хранить все ресурсы отдельной статьи рядом, в стиле БЭМ-блоков! Так уже работает организация материалов в Веб-стандартах, [см пример](https://github.com/web-standards-ru/web-standards.ru/tree/master/src/articles/coder-vs-designer).

Правило такое:

1. Каждый материал — папка с коротким его названием (слагом)
2. Внутри папки `images`, `demos` и любые другие со всем, что нужно материалу

Например: cейчас статья про `<a>` лежит в одном месте, а картинка для неё — в другом.

```
src/
  assets/
    images/
      posts/
          a/
            dogs.png
  posts/
    html/
      doka/
        a.md
```

Что я предлагаю:

```
src/
  posts/
    html/
      doka/
        a/
          images/
            dogs.png
          index.md
```

Аналогично можно поступить с кодом демок и любыми другими ресурсами, уникальными для этой статьи.

## Плюсы

- Всё сфокусировано в одном месте, легко редактировать
- Очень простые относительные ссылки: `[Картинка](images/gods.png)` вместо полного пути
- Гитхаб рендерит картинки, когда смотришь на маркдаун!

<img width="673" alt="image" src="https://user-images.githubusercontent.com/105274/101991641-33c68380-3cbf-11eb-94f0-baf95529209d.png">

## Минусы

- Если статьи шарят демки и ресурсы, это приведёт к дублированию. Но я бы этого избегал.

**Comment by nlopin** [comment]
Мне нравится такой подход. Сейчас это идет вразрез со стандартным подходом илевенти и текущей настройкой сборки. Не проблема ее переделать, но кажется этот подход заметно ее усложнит. Или я ошибаюсь? Как вы собираете эти картинки из папок? Посмотрел в проект и сходу не нашел.

**Comment by pepelsbey** [comment]
Подход как раз очень простой:

```js
config.addPassthroughCopy('src/**/*.(html|gif|jpg|png|svg|mp4|webm|zip)');
```

1. При сборке 11ty молча копирует всё ресурсное по маске из любых мест
2. Всё остальное (md, njk) обрабатывает 11ty

То есть, после этого:

Было:
```
src/
  articles/
    title/
      images/
        picture.png
      index.md
```

Стало:
```
dest/
  articles/
    title/
      images/
        picture.png
      index.html
```

**Comment by nlopin** [comment]
Огонь! попробую завтра сделать пример

**Comment by nlopin** [comment]
Я поэксперементировал и если с картинками/видосиками все работает, то с демками ситуация сложнее:

Демка тоже делается на основе шаблона и поэтому рендерится вместе со статьями. Демки в таком раскладе имеют те же родительские папки, что и статьи. Поэтому они наследуют все данные [по каскаду](https://www.11ty.dev/docs/data-cascade/). В итоге для рендеринга демки используется лейаут статьи и получается вот так:
![](https://user-images.githubusercontent.com/1469636/102139783-9ace6e80-3e5e-11eb-854f-91daff45d366.png)

Я вижу только один способ решить эту проблему — переопределять лейаут для демок. Реализовать можно по разному: прописывать вручную на уровне файла или папки, делать кодогенерацию демок или на `preBuild` шаге докидывать файлы во все папки `demos`.

**Comment by pepelsbey** [comment]
Мне кажется, что добавлять в демки свой layout — не проблема. Всегда можно завести шаблон демки. Это мне нравится гораздо больше, чем магический скрипт, который подменяет шаблоны.
