### ISSUE TITLE
Финализировать пути на сайте с учётом дальнейшего развития

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#346]
## Проблема

Сейчас у нас есть структура, на примере CSS:

```
posts/
  css/
    doka/
      active/
```

Которая приводит к таким ссылкам:

- `/posts`
- `/posts/css`
- `/posts/css/doka`
- `/posts/css/doka/active`

На мой взгляд, корневая часть `posts` попахивает личным блогом и не добавляет ничего полезного. Да, там индексная страница, куда сводится всё — но «посты» ли это и нужно ли включать её в иерархию?

## Решение

Предлагаю её немного поменять:

```
index/
css/
  doka/
    active/
```

Адреса станут проще:

- `/index`
- `/css`
- `/css/doka`
- `/css/doka/active`

## Плюсы

- Вместо «постов» появляется «индекс» (можно придумать другое), что понятнее
- Все адреса укорачиваются на одну секцию
- Все статьи по CSS, к примеру, имеют крутой короткий адрес `y-doka.site/css`

## Минусы

Если на сайте появятся другие разделы, то они будут иметь свои адреса рядом с тематическими (html, css, js) — но кажется, это не такая большая проблема. В части `/css` мы читаем про CSS, а в части `/team` про команду. Так что это и не минус, кажется.

**Comment by nlopin** [comment]
Однозначно нужно выкинуть `posts` из урлов, это критично. 

Я бы не хотел избавляться от папки `posts`. Мне она добавляет полезности — группирует весь контент в одном месте (с поправкой на другое твое предложение 🙂) и не смешивает в кучу контент, лейауты, инклуды и данные. Я сделал микроисследование и кажется мы можем сидеть сразу на двух стульях.

P.S. папку `posts` я бы переименовал во что-нибудь понятное, типа `articles`  или `materials`
