### ISSUE TITLE
Порядок выполнения - 404

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#351]
При клике на статью "Порядок выполнения" попадаю на 404 - https://y-doka.site/posts/js/doka/execution-orders 
<img width="1428" alt="Снимок экрана 2020-12-14 в 12 00 06" src="https://user-images.githubusercontent.com/50330458/102060979-ea338100-3e03-11eb-9c03-9580641a698c.png">

**Comment by nlopin** [comment]
Правильная ссылка https://y-doka.site/posts/js/doka/execution-order/
