### ISSUE TITLE
Сверстать страницу 404

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#369]
## Необходимо сверстать страницу 404

Требования
- Страница располагается в отдельном *.njk-файле [/src/404.njk](https://github.com/Y-Doka/y-doka.site/blob/master/src/404.njk)
- Стили блока написаны в *.scss-файле в папке `/src/assets/styles/components/`
- Страница свёртана по БЭМ
- Все картинки имеют alt-описание
- При вёрстке страницы стоит использовать `layout: no-aside`
- Ссылка на главную относительная и открывается в том же окне
- При вёрстке используем относительные единицы измерения
- Страница хорошо выглядит на всех размерах монитора
- При клике по ссылке переносим пользователя в корень сайта `/`

## Элементы блока
- Картинка
- Параграф с текстом и ссылкой

## Дизайн
[Посмотреть в figma](https://www.figma.com/file/gOUITTBd5ikq7sC7WGFqbL/404-public?node-id=0%3A1)

## Превью
![404](https://user-images.githubusercontent.com/50330458/102520736-0d309000-40a5-11eb-802c-24c967e47f0a.jpg)

**Comment by usmanyunusov** [comment]
@furtivite беру на себя :)

**Comment by furtivite** [comment]
Спасибо огромное!
