### ISSUE TITLE
Добавить линтер для HTML

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#374]
## Зачем

У нас нет правил написания HTML-кода, поэтому встречается:

- `<img />` и `<img>`
- `<!DOCTYPE html>` и `<!doctype html>`

Также можно линтить БЭМ, атрибуты и прочее.

## Решение

100% решения сходу нет: примеры кода будет сложновато валидировать. Поэтому можно предложить валидацию результата сборки — например, на уровне пулреквеста.

Есть живой проект [linthtml](https://github.com/linthtml/linthtml) с  [набором правил](https://github.com/linthtml/linthtml/blob/develop/docs/rules.md), которых нам должно хватить.

Дополнительно я бы прикрутил HTML-валидатор, который не столько про стиль кода, сколько про правильную вложенность и соответствие спецификации. Но это другая история.

**Comment by nlopin** [comment]
Я попробовал `linthtml` и думаю он принесет нам пользу только при внимательном выборе правил и документировании «почему». Для статей и шаблонов стоит сделать различные конфигурации. 

## Пример правила, которое нельзя включать для статей

Я тестировал разные правила на примере статьи [`html`](https://y-doka.site/html/doka/html/). В статьях мы не можем включать проверку на совпадающий закрывающий тег, потому что для называния тегов мы используем их полное написание (например, `<html>`). Вот так это выглядит при проверке статьи и включенных правилах «теги должны иметь закрывающий» и «имена открывающего»:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/1469636/102726059-ddd78880-431b-11eb-8a67-767ee26d0608.png">

## Хорошее правило

Самое полезное нам правило `tag-self-close` работает нормально и ловит кейсы:
![image](https://user-images.githubusercontent.com/1469636/102726146-6bb37380-431c-11eb-9e43-77103fbb2a9f.png)

Если будем писать про реакт, то правило придется выключать.


Я считаю, что лучше валидировать исходники статей, а не собранные страницы. Страница — это компилация кучи шаблонов, и сопоставить ошибку с исходником будет сложно. Получим много трения для контрибуторов, потому что неочевидно куда идти и что смотреть.

**Comment by nlopin** [comment]
Еще поиграл с правилами и получается очень неустойчивая конструкция. Валидация шаблонов и маркдауна чудит и ломается. 

вот какие вижу варианты:

## Минимальная проверка

Обойтись совсем базовым набором для статей:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1469636/102773889-3fced700-438a-11eb-8263-13c0936c1620.png">

Для шаблонов чуть побольше, но тоже не все правила корректно работают:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/1469636/102773935-52e1a700-438a-11eb-9b53-88a1e83a4141.png">

Из минусов — правила в шаблонах могут сломаться в любой момент из-за того, что это все-таки не html

## Проверять собранные страницы

Запускать все правила, но уже на собранных страницах. 

Главный минус такого подхода — сложно отследить, в каком файле ошибка. Это может быть любой шаблон в иерархии или маркдаун. У нас также нет гарантии, что маркдаун конвертируется в валидный html

## Проверять руками в PR

Иметь чеклист проверки HTML кода. 


Я считаю, что даже плохая автоматическая проверка лучше ручной и предлагаю делать первый вариант

**Comment by nlopin** [comment]
Запушил [ветку с настройкой](https://github.com/Y-Doka/y-doka.site/tree/feat/add-htmllint)
