### ISSUE TITLE
Добавить alt-атрибуты для изображений

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#40]
У каждого изображения есть alt-атрибуты, они позволяют понять, что изображено на картинке, если пользователь пользуется скрин-ридером, 

В проекте используется маркдаун. Посмотрите, как выглядит заполнение alt-атрибутов на примере.

---

```
Посмотрите на лого

![Логотип Дока](https://y-doka.site/assets/images/logo/logo@2x.png)

```
Посмотрите на лого

![Логотип Дока](https://y-doka.site/assets/images/logo/logo@2x.png)

---

Сейчас в качестве alt-атрибута указаны url-картинки. 

Нужно посмотреть на то, что изображено на картинках и дописать правильные alt-атрибуты.

**Comment by maximumsweet** [comment]
Внёс некоторые правки по этому issue в #221 pull request.
