### ISSUE TITLE
Система заголовков

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#404]
## Проблема

Сейчас у нас признаки какой-то системы, но она часто рассыпается. Смотрю на [список всех материалов](https://y-doka.site/all/):

- С лонгридами всё просто: пишем название словами, всё отлично
- С HTML-тегами и CSS-свойствами тоже примерно понятно

Проблемы начинаются:

- В JS-доках функции со скобками и без, с Element и без
- Перечисление то `через/слэш`, то `через / слэш`, то `через, запятую`
- В CSS очень длинные перечисления похожих псевдоклассов
- В CSS неудачная попытка изобразить тип селектора

## Решение

Мне кажется, что прописать сквозную систему, которая сработает везде у нас не получится. Но я бы поступил так:

- Обсудил общую систему: краткость, перечисления
- Отдельно с авторами и лидами направлений обсудить систему у себя
- Сформулировать принципы в руководстве и применить на практике

Я пока начал подчищать самое очевидное, что противоречит друг другу или усложняет чтение: #402, #403.

**Comment by nlopin** [comment]
Стартану обсуждение заголовков документации в разделе JS. Сейчас есть разнобой и однозначно нужно приходить к одному знаменателю. 

## Названия статей статических функций и методов

### Как показать отличие функций от методов?

Есть несколько важных моментов, которые должны быть отражены в заголовке:
* к какому объекту относится документация (push к Array, slice и к Array, и к String)
* это функция или метод объекта?

Для начинающего эта информация не жизненно важная, но она помогает людям чуть прокачанным.

Я и @pepelsbey затронули эту тему в пиаре с промисами (#403). Я посмотрел, какой подход используют разные сайты с документацией (спойлер: большинство используют [вариант из спеки Array.prototype.push](http://www.ecma-international.org/ecma-262/10.0/index.html#sec-array.prototype.push)) и сформулировал несколько идей на обсудить. 

Примеры буду приводить на функции `Array.isArray` и методе `push`. Обе статьи относятся к массиву, но одна про статическую функцию, а вторая про метод экземпляра. 

Функция `Array.isArray` так и пишется. Поэтому ее название оставляем как есть. 

У метода важно показать, что он вызывается по-другому. Мои варианты, как это можно сделать (чем выше, тем больше мне нравится):
* Array. Метод push
* Array.push + тег «метод» около названия
* array.push (маленькая буква намекает, что это переменная, но в списке статей будет смотреться странно)
* [].push()


### Указывать ли полную сигнатуру?

Другой интересный вопрос: указывать ли полную сигнатуру методов/функций в заголовке или обойтись только названием? 

Для читабельности предлагаю отбросить их, чтобы не превратиться в спеку `Array.prototype.fill ( value [ , start [ , end ] ] )`


Что думаете @pepelsbey @bespoyasov @igorkamyshev @Windrushfarer ?

**Comment by bespoyasov** [comment]
Меня смутило вот это:
«Array. Метод push».

Из-за чего я только с третьего прочтения (и взгляда на варианты по соседству) понял, что точка — это конец предложения, а не синтаксис языка. 

Я бы латиницей вообще писал только непосредственно название метода:
«Метод массива `push`».

(В списке «метод массива» будет повторяться, да, штош.)

Не знаю, насколько это (не-)правильно ¯\_(ツ)_/¯

**Comment by pepelsbey** [comment]
Есть ловушка, в которую часто попадаются люди, занимающиеся контентом: они думаю, что можно придумать единственный заголовок (или любой другой фрагмент текста), который будет удобно использовать везде. Ну или думают, что это можно автоматизировать. Нет, не получится. Нет, нельзя :) Лучше сделать по-другому.

Предположим, что у нас есть статья про какую-то фичу. Её название нужно представить в нескольких местах:

1. В заголовке на странице статьи: развёрнуто, корректно, чтобы понравиться поисковикам
2. В адресе страницы: кратко, понятно, строчными, латиницей, по-английски
3. В списке статей: кратко, без повторений, чтобы взгляд быстро цеплялся
4. В поиске: с множеством вариаций, по которым фичу могут искать

Мы не сможем решить все эти задачи одним заголовком, нам нужно завести поля в каждой доке, которые выводятся максимально эффективно для своего контекста. И придумать правила для каждого из представлений.

Я готов посидеть над статьями по вёрстке и подумать, какие представления можно придумать для каждой из них. Будет сложно сформулировать совсем чёткую систему правил, но всегда можно насобирать столько примеров, что станет понятно куда двигаться с новыми статьями.

**Comment by nlopin** [comment]
Согласен про вариации. 

Возможно я слишком оптимистично смотрю на вещи, но кажется, что все они должны делить некоторую основу (базовый заголовок?), на которую потом нанизывается зависимая от контента часть. Иначе автору придется как-то помнить про все возможные контексты заголовков.

**Comment by pepelsbey** [comment]
Думаю, нам нужно добавить обязательные поля в доки (и в шаблон) — тогда они будут торчать пустыми. Это можно и во время сборки в шаблоне проверять и кидать ошибку.
