### ISSUE TITLE
Починить вёрстку длинных заголовков на узких экранах

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#408]
![image](https://user-images.githubusercontent.com/105274/102934850-02fffe80-44b6-11eb-8864-a2d0f69d44de.png)

Вылазят и прячутся:
- Карандаш редактирования
- Теги статьи

**Comment by usmanyunusov** [comment]
@pepelsbey могу в данной задаче воспользоваться `word-break: break-word;` или же медиа запросами уменьшить шрифт?

**Comment by pepelsbey** [comment]
Эта задача больше про элементы заголовка, чем про длинный текст. Допустим, что текст переносится плохо, допустим, что нормально — но иконки и теги страдать не должны.

Задачу с переносом мы решаем отдельно.

**Comment by pepelsbey** [comment]
@ezhkov предлагаю продолжить обсуждение задачи здесь.

Мне кажется, что заголовки переносить точно нужно. Прокрутка не вариант. Сейчас у нас переносятся словарные слова на ОС, где есть словари, а случаи, вроде `getElementsByClassName`, пролетают мимо во всех случаях. Для таких случаев есть отдельный черновик пулреквеста #407, где я предложил решение. Нужно его подружить с поиском только.

А конкретно в этой задаче нужно допустить, что слова уже переносятся и понять, что делать с тегами и карандашом. Я бы лучше обратился к дизайнерам. Кажется просто кодом её не решить.

**Comment by ezhkov** [comment]
@pepelsbey Полностью согласен про дизайнеров :) У них есть доступ в репу? Как их тегнуть правильно?

**Comment by solarrust** [comment]
Дизайнеров тут не тегнуть, задачи им ставяться в Notion.

**Comment by solarrust** [comment]
ИМХО, нет смысла править отдельные элементы. Есть смысл дождаться адаптива и нормально всё сделать. В том числе и заголовки.

**Comment by nlopin** [comment]
Переоткроется, когда появится адаптивный дизайн
