### ISSUE TITLE
Поправить стили ссылок которые ещё и код

### ISSUE THREAD

**Issue by solarrust** [Y-Doka/y-doka.site#420]
Сейчас ссылки, зацепленые на инлайн код, не отличаются от просто инлайн кода визуально. Нужен дизайн, а потом и внедрение.

**Comment by furtivite** [comment]
@solarrust, если не сложно, сделай, пожалуйста, скриншоты таких ссылок?

**Comment by solarrust** [comment]
![](https://user-images.githubusercontent.com/568355/103081952-18764500-45ea-11eb-9f25-4bc62a3f4913.png)

**Comment by furtivite** [comment]
Кажется, это было сделано в #565. Теперь вот так

<img width="837" alt="Снимок экрана 2021-03-04 в 15 07 47" src="https://user-images.githubusercontent.com/50330458/109962086-d5c49d80-7cfb-11eb-9a83-f4ac54fa8144.png">
