### ISSUE TITLE
Добавить стили для таблиц в статьях

### ISSUE THREAD

**Issue by nlopin** [Y-Doka/y-doka.site#45]
В маркдауне можно создавать таблицы, но сейчас они рендерятся без стилей:

![2020-11-22 15 38 04](https://user-images.githubusercontent.com/1469636/99906690-ba97ca00-2cd8-11eb-8a76-8652e9867e2a.jpg)

Нужно придумать дизайн и реализовать.

**Comment by furtivite** [comment]
В качестве временной меры в настоящий момент используются обёртки с классами

`article__table article__table_all-half` - для двухколоночной вложенной таблицы
`article__table article__table_all-third` - для трёхколоночной вложенной таблицы
`article__table article__table_all-quarter` - для четырёхколоночной вложенной таблицы

Все колонки становятся одинаковыми по ширине. 

Стили можно посмотреть [в этом SCSS-файле](https://github.com/Y-Doka/y-doka.site/blob/master/src/assets/styles/components/_article.scss).
