### ISSUE TITLE
Какой-то хук мешает писать код

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#452]
Пытаюсь закоммитить, не хочет:

<img width="174" alt="image" src="https://user-images.githubusercontent.com/105274/104919174-e072df80-59a6-11eb-8702-319210a8efc2.png">

До этого он мне сам исправил на такое, но это не то, что мне нужно:

<img width="165" alt="image" src="https://user-images.githubusercontent.com/105274/104919746-cdacda80-59a7-11eb-995a-a78488e38a6c.png">

**Comment by pepelsbey** [comment]
@nlopin не ты ли писал этот хук? :)

**Comment by nlopin** [comment]
Мамой клянусь, это linthtml

**Comment by pepelsbey** [comment]
@nlopin мы можем не трогать MD-файлы преттиером? Это всё-таки не код в прямом виде, это контент. И нам важно иметь возможность текст и примеры кода в разном стиле, даже ошибочном. Там достаточно EditorConfig. Я бы вообще оставил Prettier только для JS.

**Comment by nlopin** [comment]
Хочется не контролировать руками одинаковость примеров кода на js. 

Ты прав, разделы html и css можно добавить в исключения. Он там скорее мешает
