### ISSUE TITLE
Поправить блокирующие запросы

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#48]
Сейчас [в главном файле стилей](https://y-doka.site/assets/styles/main.css) Доки три импорта с двух доменов:

```css
@import url(https://rsms.me/inter/inter.css);
@import url(//fonts.googleapis.com/css2?family=Inter&display=swap);
@import url(https://fonts.googleapis.com/css2?family=Roboto&display=swap);
```

Кроме того, что они ведут на внешние домены, которые не прогреты — эти запросы блокирующие. То есть пока браузер не загрузит каждый этот файл, даже если он распарсил весь main.css, он ничего не нарисует.

> [First Contentful Paint: 2.5 s (mobile)](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fy-doka.site%2F&tab=mobile)

Решения два:

1. Быстро: положить импорты в HTML сразу после главного файла и прогреть домены
2. Подольше: захостить шрифты самостоятельно

Могу сделать пулреквесты по обоим вариантам.

**Comment by furtivite** [comment]
Думаю, что лучше решение с хостом шрифтов. Это позволяется лицензией, местом, меньше запросов будет.

**Comment by usmanyunusov** [comment]
@furtivite захостить шрифты прямо в репозиторий?

**Comment by pepelsbey** [comment]
@usmanyunusov ага, план такой.

Я ещё один CSS-файл пропустил, который не шрифт: https://unpkg.com/prismjs@1.20.0/themes/prism-okaidia.css

Его бы взять из npm, наверное, и склеивать при сборке, например.
