### ISSUE TITLE
Починить оформление кода примеров на JavaScript

### ISSUE THREAD

**Issue by nlopin** [Y-Doka/y-doka.site#480]
Для оформления блоков кода на js мы используем нотацию ` ```javascript`, но часть статей оформлена неверно блоками ` ```jsx `

В результате получается корявая подсветка синтаксиса:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/1469636/106366687-ec16bc80-633d-11eb-8fb4-685d15c8118f.png">

Нужно найти такие неверные блоки в папке `posts/js` и исправить.

**Comment by pepelsbey** [comment]
Везде, где я исправлял jsx, я писал js, а не javascript, так короче :)

**Comment by pepelsbey** [comment]
Хотя погоди, я же уже это делал в #434 и с тех пор новых не появилось, я поискал по проекту

**Comment by nlopin** [comment]
@pepelsbey в статье [«парадигмы программирования»](https://y-doka.site/js/long/programming-paradigms/) или [«ООП»](https://y-doka.site/js/long/oop/) странные выделения операторов присваивания, двоеточий и всего такого.

Возможно дело в стилях

**Comment by pepelsbey** [comment]
Там всё в порядке с языком `class="language-js"`, проблема в стилях.

**Comment by pepelsbey** [comment]
Я бы под это дело ещё поискал тему подсветки, которая нам будет будет ближе по стилю и заодно не будет иметь таких проблем.

**Comment by pepelsbey** [comment]
[Список тем для Prism](https://github.com/PrismJS/prism-themes), которые можно попробовать. А ещё можно просто попробовать поправить тему!

**Comment by solarrust** [comment]
Если бы этот инструмент устраивал нас на 100500% и проблема была бы только с редкой неправильной подсветкой, то я бы согласилась на правку темы руками. Но давайте обсудим альтернативы?

**Comment by pepelsbey** [comment]
Окей, а какие есть проблемы? Я просто только что услышал, что проблемы есть. Не видел ишью, по крайней мере.

**Comment by nlopin** [comment]
Давайте соберем проблемы в [дискуссии](https://github.com/Y-Doka/y-doka.site/discussions/495), чтобы сделать взвешенное решение.
