### ISSUE TITLE
Дока про LocalStorage

### ISSUE THREAD

**Issue by nlopin** [Y-Doka/y-doka.site#485]
Рассказать зачем он нужен, как пользоваться и какие есть ограничения

- [ ] Сослаться на [статью со сравнением систем хранения](https://github.com/Y-Doka/y-doka.site/issues/487)

**Comment by akellbl4** [comment]
@Windrushfarer попробую сделать если ты еще не начал ;)

**Comment by Windrushfarer** [comment]
Снимаю тогда с себя :)
