### ISSUE TITLE
Поправить сборку чтобы не пересобирались все файлы

### ISSUE THREAD

**Issue by solarrust** [Y-Doka/y-doka.site#497]
При локальной разработке не очень удобно, что при любых изменениях пересобираются абсолютно все файлы проекта. Было бы круто, если возможно, обновлять только тот файл, который поменялся.

**Comment by usmanyunusov** [comment]
В 0.11.0 версии для 11ty зарезили **Incremental Builds**. Дополнительные разработки по ней еще идут.

Она включается с помощью флага `--incremental`
Попробовал на проекте DEV сборку с этим флагом и без

Вот что получил:
``` javascript
// без флага --incremental
[eleventy:dev] Writing dist/tags/sprint-14/index.html from ./src/posts/posts-by-tags.njk.
[eleventy:dev] Writing dist/tags/sprint-8/index.html from ./src/posts/posts-by-tags.njk.
[eleventy:dev] Writing dist/tags/jsTools/index.html from ./src/posts/posts-by-tags.njk.
[eleventy:dev] Writing dist/tags/jsDoka/index.html from ./src/posts/posts-by-tags.njk.
```
``` javascript
// с флагом --incremental
[eleventy:dev] Writing dist/tags/sprint-14/index.html from ./src/posts/posts-by-tags.njk.
[eleventy:dev] Skipping dist/tags/sprint-8/index.html from ./src/posts/posts-by-tags.njk.
[eleventy:dev] Skipping dist/tags/jsTools/index.html from ./src/posts/posts-by-tags.njk.
[eleventy:dev] Skipping dist/tags/jsDoka/index.html from ./src/posts/posts-by-tags.njk.
```
Из логов заметно, что в первом случае собираются все файлы, а во втором – только измененные, пропуская остальные.

Явных изменений при разработке не заметил. Так как hot reload все равно запускается после финиша самой 11ty.

**Comment by nlopin** [comment]
Исправлено в репозитории платформы
