### ISSUE TITLE
Поправить autor на author

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#50]
Кажется это началось [в инклюде авторской карточки](https://github.com/Y-Doka/y-doka.site/tree/master/src/includes/autors) и продолжилось в других местах по примеру: [166 вхождений](https://github.com/Y-Doka/y-doka.site/search?q=autors) в коде. Если это не шутка, а опечатка — сделаю пулреквест.

**Comment by furtivite** [comment]
Это опечатка.
