### ISSUE TITLE
Сделать шаблон для демок

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#506]
Так случилось, что все наши переработанные демки сейчас — это невалидные HTML-документы, которые рендерятся браузерами в quirks mode и могут работать не так, как надо из-за этого. Кроме того, что это в принципе неправильно. Не уверен насчёт других демок, кстати.

Вот _полный_ код [одной переработанной демки](https://y-doka.site/demos/a/basic/):

```html
<style>@import url("https://fonts.googleapis.com/css2?family=Roboto&display=swap");

body {
  margin: 0;
}

.article__code {
  padding: 5%;
  background-color: #18191c;
  color: #ffffff;
  text-align: center;
  font-family: "Roboto", sans-serif;
}

a {
  font-size: 24px;
  color: #ffffff;
  text-decoration-color: #1a5ad7;
}</style><div class="article__code"><a href="http://www.yandex.ru/">Яндекс</a></div>
```

Тут нет ни доктайпа, ни языка, ни базовой структуры страницы.

Было бы круто, если бы это выгдядело иначе:

```html
<!DOCTYPE html>
<html lang="ru">
<head>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto&display=swap">
  <style>
    body {
      margin: 0;
    }
    
    .article__code {
      padding: 5%;
      background-color: #18191c;
      color: #ffffff;
      text-align: center;
      font-family: "Roboto", sans-serif;
    }
    
    a {
      font-size: 24px;
      color: #ffffff;
      text-decoration-color: #1a5ad7;
    }
  </style>
</head>
<body>
  <div class="article__code">
    <a href="http://www.yandex.ru/">Яндекс</a>
  </div>
</body>
</html>
```

По сути, нам нужно придумать несложный шаблон для типовой демки. Учитывая, что наши демки будут храниться вместе с контентом и важно иметь возможность их видеть как есть без сборки — я бы стремился к демке-файлу. Например:

```
src/
  html/
    a/
      demos/
        basic/
          index.html
```

Сейчас демка это файл `basic.njk` и `basic.css`, причём файл стилей инклюдится средствами Nunjucks, то есть для сборки и работы демки нужен Eleventy.

На мой взгляд, можно не дожидаться разделения репозиториев и начать работу по рефакторингу демок уже сейчас.

Что скажете?

**Comment by pepelsbey** [comment]
Я сделаю пулреквест, который рефакторит упомянутую демку.
И по его примеру можно будет начать рефакторить и другие.

**Comment by pepelsbey** [comment]
Отдельная задача — избавиться от инклюдов внешних шрифтов, но это мы продумаем в новой архитектуре платформы :)

**Comment by nlopin** [comment]
> Отдельная задача — избавиться от инклюдов внешних шрифтов, но это мы продумаем в новой архитектуре платформы :)

С этим может быть проблема, потому что сейчас демки рендерятся в айфреймах.

**Comment by nlopin** [comment]
Мне не очень нравится идея файла-демки, потому что она работает только для простых случаев. Если будет сложный CSS или JS, то поддерживать демку будет тяжелее. 

В любом случае, раз это обычный html, то у нас такая возможность остается из коробки ценой дополнительного запроса (в этом контексте njk побеждает, потому что мы платим при сборке, а не на клиенте).

**Comment by pepelsbey** [comment]
> С этим может быть проблема, потому что сейчас демки рендерятся в айфреймах.

Я имел в виду совсем внешние, гугловые. У нас на сайте уже свои шрифты. Надо придумать, как их удобно в демки подключать.

> Мне не очень нравится идея файла-демки
> Если будет сложный CSS или JS, то поддерживать будет тяжелее

Я не буквально говорил и скорее хотел избавиться от сборки и сложных зависимостей. Если есть внешние ресурсы или обёмные части у демки — всё легко кладётся в свою папку и подключается средствами браузера. Но если она простая (10 строчек JS, 10 строчек CSS), то лучше конечно всё в одном файле свести для наглядности.
