### ISSUE TITLE
Переписать демку к list-style-type

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#507]
Так вышло, что [демка list-style-type](https://codepen.io/Realetive/pen/YzqVJXY) для [доки list-style-type](https://y-doka.site/css/doka/list-style-type/) сложнее, чем стоило бы. Там React и React DOM на основе JSON для демонстрации очень простого CSS-свойства, которое будут смотреть новички. И не хочется их пугать фреймворком.

@nlopin меня поддержал, кажется это нужно либо упростить, либо переписать. Варианты:

- На CSS и `@keyframes`
- На ванильном JS

Сама идея очень клёвая, так что я бы не пытался даунгрейдить до статической демки. Просто сделал бы настоящий HTML-список и оживил бы его на CSS, либо на ванильном скрипте.

Всплыло во время ревью #467, там лёгкий рестайлинг демки. Стоит взять его за основу.

**Comment by nlopin** [comment]
Офигенная задача, чтобы застримить ее решение.
