### ISSUE TITLE
Согласие на перенос кода Усмана Юнусова

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#543]
Привет! 

Команда Доки планирует изменить инфраструктуру кода и нам необходимо перенести часть (или весь) код, который был тобой вложен в проект в новый репозиторий [в рамках сообщества Доки](https://github.com/Y-Doka). 

Чтобы исключить недопонимание и дальнейшие юридические вопросы по этому процессу, поскольку они отходят от правил, принятых стандартной MIT License, прошу @usmanyunusov подтвердить право сообщества на такое действие. 

Комментария: «Подтверждаю» — достаточно. 

Большое спасибо за вклад в проект.

**Comment by usmanyunusov** [comment]
Подтверждаю

**Comment by furtivite** [comment]
Спасибо огромное за вклад в проект!
