### ISSUE TITLE
Разрешить другие значения display

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/y-doka.site#548]
[В статье про `display`](https://y-doka.site/css/doka/display/#%D0%BA%D0%B0%D0%BA-%D1%8D%D1%82%D0%BE-%D0%BF%D0%BE%D0%BD%D1%8F%D1%82%D1%8C) (и возможно где-то ещё) менее распространённые значения свойства `display` зря умаляются: они не устарели и имеют нормальную поддержку. Они тоже могут быть полезными, задачи бывают очень разные :)

> Существует множество других значений, но большинство из них либо устарели, либо не имеют хорошей поддержки. Если встретите в коде следующие значения, то не пугайтесь: `inline`, `inline-table`, `list-item`, `run-in`, `table`, `table-caption`, `table-cell`, `table-column-group`, `table-column`, `table-footer-group`, `table-header-group`, `table-row`, `table-row-group`. Все эти значения заменяет семантическая разметка. Создавать те же таблицы на дивах и при помощи стилей считается очень плохой практикой. Не надо так! 

Я бы не был так резок и «разрешил» то, что вполне полезно. Мне кажется, можно и вовсе без этого абзаца.

**Comment by solarrust** [comment]
Пометка себе: Речь о статье про `display`.

**Comment by pepelsbey** [comment]
Упс, поправил описание и добавил ссылку.

**Comment by solarrust** [comment]
Фиксить после слияния #538
