### ISSUE TITLE
Поправить опечатки в статье try...catch

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/y-doka.site#575]
- исправить в тексте 'try..catch' на 'try...catch'
- поправить название на 'try...catch'

**Comment by furtivite** [comment]
@nlopin ок?

**Comment by nlopin** [comment]
да. Можно было сразу исправить

**Comment by furtivite** [comment]
@nlopin, тогда не буду заливать такие задачи отдельным issue, сразу поправлю в том issue, где заметил.
