### ISSUE TITLE
Повысить контрастность ссылок

### ISSUE THREAD

**Issue by bespoyasov** [Y-Doka/y-doka.site#690]
Давно хотел написать, но всё забывал. А сейчас понадобилось поискать ссылку в тексте статьи и снова наткнулся на проблему: у нас очень неконтрастные ссылки.

Пример, с первого взгляда определить, где ссылка практически невозможно:
<img width="899" alt="«Screenshot» 2021-04-03 at 15 16 30" src="https://user-images.githubusercontent.com/9102374/113478153-b69e6480-948f-11eb-97bd-48f902e39c09.png">

Варианты:
- более контрастные цвет для ссылок (особенно — посещённых, сейчас они почти как текст по цвету);
- подчёркивание (надеюсь, я тут не разожгу холивар 😃).

**Comment by pepelsbey** [comment]
Если мы будем делать документацию, где читаемость важнее всего, то нам нужно будет подчёркивать ссылки. Но это уже будет ближе к разговору с дизайнерами. Никакой контраст, к сожалению, не поможет при сложностях с цветовым восприятием.

**Comment by bespoyasov** [comment]
Ну да. Я в целом скорее ишью открыл, чтобы проблему подсветить 🙂
