### ISSUE TITLE
Гайд по цветам в вебе

### ISSUE THREAD

**Issue by solarrust** [Y-Doka/y-doka.site#73]

**Comment by ezhkov** [comment]
Насколько оригинальным должен быть материал? Можно ли переработать [эту](https://css-tricks.com/nerds-guide-color-web/) статью?

**Comment by pepelsbey** [comment]
На мой взгляд «перерабатывать» (или вольно переводить) статьи стыдновато. Если там такая же структура, демки и прочее — лучше не надо.
